// Generated by https://quicktype.io

export interface Planta {
  id: string;
  nombre_comun: string;
  nombre_cientifico: string;
  tipo: string;
  altura_maxima: number;
  clima: string;
  sustrato_siembra: string;
}